run:
    zig run -O ReleaseFast gomoku.zig

test:
    zig test -O ReleaseFast gomoku_test.zig

wasm: wasm-build
    bun gomoku.js

wasm-build:
    zig build-exe -O ReleaseFast -target wasm32-freestanding \
    -fno-entry \
    --export=play \
    -femit-bin=gomoku.wasm gomoku.zig
    ls -al gomoku.wasm
