abc:

run:
    uv run main.py

prebuild:
    uv pip install --upgrade build

build:
    python -m build

install-wheel:
    uv pip install dist/custom_extension-0.1.0-cp313-cp313-macosx_11_0_arm64.whl

install-wheel-inplace:
    uv pip install -e .

prebuild-setuptools:
    uv sync
    python setup.py build_ext --inplace
    uv pip install .

clean:
    git clean -Xf
