[project]
name = "python-http2-hypercorn"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.8",
    "httpx>=0.28.1",
    "humanize>=4.11.0",
    "hypercorn>=0.17.3",
    "python-multipart>=0.0.20",
]
