[project]
name = "python-pdm"
version = "0.1.0"
authors = [{ name = "Alexander Demin", email = "a@demin.page" }]
dependencies = ["icecream>=2.1.3"]
requires-python = "==3.12.*"
readme = "README.md"
license = { text = "MIT" }


[tool.pdm]
distribution = false
