set unstable := true

default: build

export COMMIT := shell('git rev-parse --short HEAD')

build:
    bun run build
    go build -o ./exe main.go    

[confirm('all good?')]
commit:
    @echo {{ COMMIT }}

FLAGS := "default"

print +args:
    @echo {{ FLAGS }} ${HOME} {{ args }}

js:
    #!/usr/bin/env bun
    console.log("bun!")
