abc:

wasm-build:
    zig build-exe -O ReleaseSmall -target wasm32-freestanding \
    -fno-entry \
    --export=init \
    --export=deinit \
    --export=remaining \
    --export=tries \
    --export=guess \
    -femit-bin=mastermind.wasm wasm.zig

wasm: wasm-build
    bun index.js

run:
    zig run main.zig
