FROM denoland/deno as deno

FROM public.ecr.aws/lambda/provided:al2

COPY --from=deno /usr/bin/deno /usr/bin/deno

ENV DENO_DIR=/var/task/.cache

COPY lambda.ts pdf.ts /var/task/

RUN DENO_DIR=/var/task/.cache \
    deno cache \
    --no-lock \
    --node-modules-dir=true \
    --vendor=true \
    /var/task/lambda.ts

ENTRYPOINT [ "/usr/bin/deno" ]
CMD [ "run", "-A", \
    "--no-lock", \
    "--no-check", \
    "--no-remote", \
    "--cached-only", \
    "--node-modules-dir=true", \
    "--vendor=true", \
    "/var/task/lambda.ts" \
    ]
