default: clean build run

T := "\\"

run := 'dosbox-x -nolog -c "mount c: ./c" -c "c:"'
batch := run + ' -silent -exit'

build:
    {{ batch }} -c "tpc go.pas /ETP7 >output.txt"
    @if grep -i "error" c/OUTPUT.TXT; then exit 1; fi

clean:
    {{ batch }} -silent -exit -c "del TP7{{ T }}go.exe"

run:
    {{ run }} -c go.exe -exit

ide:
    {{ run }} -exit -c turbo

cmd:
    {{ run }}