default: clean build run

run := 'dosbox-x -nolog -c "mount c: ./c" -c "c:" -c "PATH=%PATH%;C:\BP\BIN"'
silent := run + ' -silent -exit'
visual := run + ' -fastlaunch -set output=ttf'
install := visual + ' -c "mount x: ./x" -c "PATH=%PATH%;C:\BP\BIN"'

build:
    {{ silent }} -c "bpc /m cref.pas >output.txt"
    @if grep -i "error" c/OUTPUT.TXT; then exit 1; fi

clean:
    {{ silent }} -c "del *.exe" -c "del output.txt" -c "del *.tpu"

run:
    {{ visual }} -exit -c cref.exe

ide:
    {{ visual }} -exit -c "turbo go.pas"

cmd:
    {{ visual }}

install:
    {{ install }}
