apiVersion: v1
kind: PersistentVolume
metadata:
  name: common-persistent-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  # claimRef:
  #   namespace: default
  #   name: common-persistent-volume-claim
  gcePersistentDisk:
    pdName: DISK_NAME
