name: gomoku
on:
    push:
        branches: ["main"]
        paths: ["gomoku/**"]
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: extractions/setup-just@v3
            - uses: actions/setup-go@v6
              with:
                  go-version: "1.25"
            - run: >
                  cd gomoku &&
                  just test
