name: pascal-parser
on:
    push:
        branches: ["main"]
        paths: ["pascal-parser/**"]
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.13"
            - run: >
                  cd pascal-parser &&
                  python3 test_main.py
